dailigram/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
# from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views
from diary import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('diary/', include('diary.urls')),
    path('', RedirectView.as_view(url='/login/')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout')
]

diary/urls.py
from django.urls import path
from diary import views
from django.contrib.auth.decorators import login_required

app_name = 'diary'
urlpatterns = [
    path('register/', views.UserFormView.as_view(), name='register'),
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('create_page/', login_required(views.CreatePage.as_view()), name='create_page'),
    path('format/', login_required(views.Format.as_view()), name='format'),    
    path('<int:pk>/', login_required(views.DetailView.as_view()), name='detail'),
    path('<int:pk>/delete/', login_required(views.DeleteDiary.as_view()), name='delete_diary')

]

diary/models.py
from django.db import models
from django.urls import reverse
import datetime


class Diary(models.Model):
    username = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('diary:index')


class Tag(models.Model):
    name = models.CharField(
        max_length=200, help_text='Enter a tag (e.g. Love, Happy, Sad)')

    def __str__(self):
        return self.name


class Page(models.Model):
    diary = models.ForeignKey(Diary, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=15)
    tag = models.ForeignKey(Tag, on_delete=models.SET_NULL, null=True)
    story = models.TextField()
    date = models.CharField(max_length=10)
    picture = models.FileField()

    def __str__(self):
        return f'{str(self.date)}, {self.diary}, {self.tag}'

    def get_absolute_url(self):
        return reverse('diary:index')

diary/forms.py
from django.contrib.auth.models import User
from .models import Page, Diary, Tag
from django.forms import ModelForm, Textarea, TextInput, PasswordInput
from django import forms


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
          'username': TextInput(attrs={
              'style': 'margin: 0 auto'}),

          'password': PasswordInput(attrs={
            'style': 'margin: 0 auto'}),
        }
        help_texts = {'username': "Enter between 6-20 letters",}
    

class PageForm(forms.ModelForm):

    class Meta:
        model = Page
        fields = ['title', 'story', 'tag']
        widgets = {
          'story': Textarea(attrs={'rows':15, 'cols':60, 'style': 'width: 100%'}),
        }

diary/views.py
from diary.models import Tag, Page, Diary
from django.views import generic, View
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from .forms import UserForm, PageForm
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from django.urls import reverse_lazy
from utility.imgur import ImgurUtil
from django.db.models import Q
from django import forms
import requests
import datetime


def login_user(request):
    """
    If the user is not authenticated, get user's request and execute login.
    """
    if not request.user.is_authenticated:
        form = UserForm(request.POST or None)
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    HttpResponseRedirect(reverse('diary:index'))
                else:
                    return render(request, 'registration/login.html', {'form': form})
            else:
                messages.error(request, 'username or password is not correct')
                return render(request, 'registration/login.html', {'form': form})
        else:
            return render(request, 'registration/login.html', {'form': form})

    return HttpResponseRedirect(reverse('diary:index'))


def logout_user(request):
    """
    Function to logout user and redirect to login page. 
    """
    logout(request)
    return HttpResponseRedirect('/login')


class IndexView(generic.ListView):
    template_name = 'diary/index.html'
    context_object_name = 'all_pages'

    def get_queryset(self):
        """
        Get the queryset to look an object up against.
        """
        username = self.request.user.username
        diaries = Diary.objects.filter(username=username)
        page = Page.objects.all()
        imgurUtil = ImgurUtil()

        query = self.request.GET.get("q")
        if diaries == page[0].diary:
            if query:
                return page.filter(
                    Q(title__icontains=query)
                    ).distinct()

        if len(diaries) == 0:
            Diary.objects.create(username=username)

        return Page.objects.filter(diary__username=username)


class DetailView(generic.DetailView):
    model = Page
    template_name = 'diary/detail.html'
    queryset = Page.objects.all()

    def get_queryset(self):
        """
        Get the queryset to look an object up against. This will only display the specific diary's username.
        """
        username = self.request.user.username
        return Page.objects.filter(diary__username=username)


class Format(View):
    template_name = 'diary/format.html'

    def get(self, request):
        return render(request, self.template_name)


class CreatePage(View):
    form_class = PageForm
    template_name = 'diary/create_page.html'

    def get(self, request):
        form = self.form_class(None)

        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            try:
                request.FILES['myfile']
            except:
                messages.error(
                    request, 'Please select a file.')
                return HttpResponseRedirect("/diary/create_page")

            username = self.request.user.username
            diary = Diary.objects.filter(username=username)
            
            error = self.__check_title(form, diary)

            if (error is not None):
                messages.error(request, error)
                return HttpResponseRedirect("/diary/create_page")

            page = form.save()
            imgurUtil = ImgurUtil()
            my_file = request.FILES['myfile']
            page.diary = diary[0]
            page.date = str(datetime.date.today())
            description = str(page.diary) + ':' + \
                str(page.id) + ':' + page.date
            response = imgurUtil.upload_image_locally(description, my_file)
            if(response.status_code == requests.codes.ok):
                uploader_url = response.json()["data"]["link"]
                page.picture = uploader_url
                page.save()

            else:
                messages.error(
                    request, 'Please select a valid file.')
                return HttpResponseRedirect("/diary/create_page")
        return HttpResponseRedirect("/diary/")

    def __check_title(self, form, diary):
        for page in Page.objects.all():
            if page.diary == diary[0]:
                if page.title == form.cleaned_data.get("title"):
                    return 'You already used this title. Please try another one.'


class DeleteDiary(DeleteView):
    form_class = PageForm
    model = Page
    success_url = reverse_lazy('diary:index')

    def delete(self, request, *args, **kwargs):
        """
        Function to delete picture from database and imgur.
        """
        imgurUtil = ImgurUtil()
        page = self.get_object()
        description = str(page.diary) + ':' + str(page.id) + ':' + page.date
        image_hash = imgurUtil.get_image_hash(description)
        imgurUtil.delete_image(image_hash)
        page.delete()
        return HttpResponseRedirect('/diary/')


class UserFormView(View):
    form_class = UserForm
    template_name = 'registration/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('/login')

        return render(request, self.template_name, {'form': form})

diary/templates/diary/create_page.html
{% extends "base.html" %}

{% block content %}
<div style="font-family: 'Ubuntu', sans-serif;">
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
{% for message in messages %}
  <div class="alert alert-warning text-center">
  <a class="close" href="#" data-dismiss="alert">×</a><strong>Sorry!</strong> {{ message }}
</div>
{% endfor %}
</div>

<div class="container" style="font-family: 'Ubuntu', sans-serif;
border: 1.5px solid black; border-radius: 15px; padding-bottom: 20px; ">
  <br>
  <div align="center" style="background-color: rgb(180, 180, 180); border-radius: 15px;">
    <h1>Create Diary</h1>
  </div><br>
  <form onsubmit="disableUploadButton()" class="form-horizontal" method="post" enctype="multipart/form-data" autocomplete="off">
    <h5>
    {% csrf_token %}
    {{form.as_p}}
      Picture: 
      <input type="file" name="myfile" id="id_picture"><br><br>
    </h5>
      <h4><button id="upload-button" type="submit" class="btn btn-dark btn-lg btn-block">Upload</button></h4> 
  </div>

{% endblock %}

diary/templates/diary/detail.html
{% extends 'base.html' %} {% block content %}
<div style="font-family: 'Ubuntu', sans-serif; text-align: center;">
    <div style="word-wrap: break-word; padding: 75px">
        <h1>{{ page.title }}</h1>
    </div>
    <div>
        <img src="{{ page.picture }}" class="img-responsive" style='height: 50%; width: 50%; object-fit: contain'>
        <div style="padding: 100px; word-wrap: break-word;">
            {{ page.story }}
        </div>
    </div>
</div>
<div class="bottomright">{{ page.date }}</div>
{% endblock %}

diary/templates/diary/index.html
{% extends 'base.html' %} {% load static %} {% block content %} {% if user.is_authenticated %}

<body>
    <form class="form-inline my-2 my-lg-0 " style="font-family: 'Ubuntu', sans-serif; padding-left: 10px; width: 380px">
        <input class="form-control mr-sm-2" name="q" value="{{ request.GET.q }}" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-dark my-2 my-sm-0" type="submit">Search</button>
    </form><br>

<div style="font-family: 'Ubuntu', sans-serif;" class="container-fluid">
    <div align="center">
        <h2 class="text-center" style='display: inline; border:2px black solid; font-size:25px; padding: 9px;'>
            <img src="{% static 'pictures/icon.jpg' %}" height="30px" width="35px"> {{ user.username }}'s diary</h2>
    </div>
    <br><br>
    <div style="border: 2px white solid; border-radius: 100%; width: 230px; height: 230px; margin-left: auto; margin-right: auto; ">
        <img src="{% static 'pictures/user.png' %}" height="180px" width="180px" class="rounded-circle" style='height: 100%; width: 100%; overflow: hidden;'>
    </div>
    <br><br>
    <div class="row text-center">
        {% if all_pages %} {% for page in all_pages %}
        <div class="col-sm-3 col-lg-3" style="min-width:320px;">
            <div style=" padding-bottom: 30px;">
                <div class="thumbnail" class="caption" style='border:1.5px rgb(15, 9, 9) solid; overflow: hidden; block:inline; padding-bottom: 10px; min-width: 230px;'>
                    <a href=" {% url 'diary:detail' page.id %}">
                            <img src="{{ page.picture }}" style=" width: auto; height: auto; max-width: 100%; height: 200px; margin: 0 auto;" />
                    </a>
                    <div style="word-wrap: break-word;">
                        <h2>{{ page.title }}</h2>
                    </div>
                    <div>
                        {% comment %} <h2>{{ page.diary }}</h2> {% endcomment %}
                        {% comment %} <h3>{{ page.tag }}</h3> {% endcomment %}
                        {% comment %} <h4>{{ page.story }}</h4> {% endcomment %}
                        <h4>{{ page.date }}</h4>
                    </div>

                    <!-- delete button -->
                    <form onsubmit="disableDeleteButton( {{page.id}} )" action="{% url 'diary:delete_diary' page.id%} " method="post">
                        {% csrf_token %}
                        <input type="hidden" name="page_id" value="{{ page.id }}" />
                        <button id="{{page.id}}" class="btn btn-secondary" type="submit">Delete</button>
                    </form>
                </div>
            </div>
        </div>

        {% endfor %} {% endif %}
    </div>
</div>
{% else %}
<a href="{% url 'login'%}">Login</a>
{% endif %} {% endblock %}
</body>