dailigram/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView
# from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.auth import views as auth_views
from diary import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('diary/', include('diary.urls')),
    path('', RedirectView.as_view(url='/login/')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout')
]

diary/urls.py
from django.urls import path
from diary import views
from django.contrib.auth.decorators import login_required

app_name = 'diary'
urlpatterns = [
    path('register/', views.UserFormView.as_view(), name='register'),
    path('', login_required(views.IndexView.as_view()), name='index'),
    path('create_page/', login_required(views.CreatePage.as_view()), name='create_page'),
    path('format/', login_required(views.Format.as_view()), name='format'),    
    path('<int:pk>/', login_required(views.DetailView.as_view()), name='detail'),
    path('<int:pk>/delete/', login_required(views.DeleteDiary.as_view()), name='delete_diary')

]

diary/models.py
from django.db import models
from django.urls import reverse
import datetime


class Diary(models.Model):
    username = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('diary:index')


class Tag(models.Model):
    name = models.CharField(
        max_length=200, help_text='Enter a tag (e.g. Love, Happy, Sad)')

    def __str__(self):
        return self.name


class Page(models.Model):
    diary = models.ForeignKey(Diary, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=15)
    tag = models.ForeignKey(Tag, on_delete=models.SET_NULL, null=True)
    story = models.TextField()
    date = models.CharField(max_length=10)
    picture = models.FileField()

    def __str__(self):
        return f'{str(self.date)}, {self.diary}, {self.tag}'

    def get_absolute_url(self):
        return reverse('diary:index')

diary/forms.py
from django.contrib.auth.models import User
from .models import Page, Diary, Tag
from django.forms import ModelForm, Textarea, TextInput, PasswordInput
from django import forms


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
          'username': TextInput(attrs={
              'style': 'margin: 0 auto'}),

          'password': PasswordInput(attrs={
            'style': 'margin: 0 auto'}),
        }
        help_texts = {'username': "Enter between 6-20 letters",}
    

class PageForm(forms.ModelForm):

    class Meta:
        model = Page
        fields = ['title', 'story', 'tag']
        widgets = {
          'story': Textarea(attrs={'rows':15, 'cols':60, 'style': 'width: 100%'}),
        }

diary/views.py
from diary.models import Tag, Page, Diary
from django.views import generic, View
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from .forms import UserForm, PageForm
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from django.urls import reverse_lazy
from utility.imgur import ImgurUtil
from django.db.models import Q
from django import forms
import requests
import datetime


def login_user(request):
    """
    If the user is not authenticated, get user's request and execute login.
    """
    if not request.user.is_authenticated:
        form = UserForm(request.POST or None)
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    HttpResponseRedirect(reverse('diary:index'))
                else:
                    return render(request, 'registration/login.html', {'form': form})
            else:
                messages.error(request, 'username or password is not correct')
                return render(request, 'registration/login.html', {'form': form})
        else:
            return render(request, 'registration/login.html', {'form': form})

    return HttpResponseRedirect(reverse('diary:index'))


def logout_user(request):
    """
    Function to logout user and redirect to login page. 
    """
    logout(request)
    return HttpResponseRedirect('/login')


class IndexView(generic.ListView):
    template_name = 'diary/index.html'
    context_object_name = 'all_pages'

    def get_queryset(self):
        """
        Get the queryset to look an object up against.
        """
        username = self.request.user.username
        diaries = Diary.objects.filter(username=username)
        page = Page.objects.all()
        imgurUtil = ImgurUtil()

        query = self.request.GET.get("q")
        if diaries == page[0].diary:
            if query:
                return page.filter(
                    Q(title__icontains=query)
                    ).distinct()

        if len(diaries) == 0:
            Diary.objects.create(username=username)

        return Page.objects.filter(diary__username=username)


class DetailView(generic.DetailView):
    model = Page
    template_name = 'diary/detail.html'
    queryset = Page.objects.all()

    def get_queryset(self):
        """
        Get the queryset to look an object up against. This will only display the specific diary's username.
        """
        username = self.request.user.username
        return Page.objects.filter(diary__username=username)


class Format(View):
    template_name = 'diary/format.html'

    def get(self, request):
        return render(request, self.template_name)


class CreatePage(View):
    form_class = PageForm
    template_name = 'diary/create_page.html'

    def get(self, request):
        form = self.form_class(None)

        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            try:
                request.FILES['myfile']
            except:
                messages.error(
                    request, 'Please select a file.')
                return HttpResponseRedirect("/diary/create_page")

            username = self.request.user.username
            diary = Diary.objects.filter(username=username)
            
            error = self.__check_title(form, diary)

            if (error is not None):
                messages.error(request, error)
                return HttpResponseRedirect("/diary/create_page")

            page = form.save()
            imgurUtil = ImgurUtil()
            my_file = request.FILES['myfile']
            page.diary = diary[0]
            page.date = str(datetime.date.today())
            description = str(page.diary) + ':' + \
                str(page.id) + ':' + page.date
            response = imgurUtil.upload_image_locally(description, my_file)
            if(response.status_code == requests.codes.ok):
                uploader_url = response.json()["data"]["link"]
                page.picture = uploader_url
                page.save()

            else:
                messages.error(
                    request, 'Please select a valid file.')
                return HttpResponseRedirect("/diary/create_page")
        return HttpResponseRedirect("/diary/")

    def __check_title(self, form, diary):
        for page in Page.objects.all():
            if page.diary == diary[0]:
                if page.title == form.cleaned_data.get("title"):
                    return 'You already used this title. Please try another one.'


class DeleteDiary(DeleteView):
    form_class = PageForm
    model = Page
    success_url = reverse_lazy('diary:index')

    def delete(self, request, *args, **kwargs):
        """
        Function to delete picture from database and imgur.
        """
        imgurUtil = ImgurUtil()
        page = self.get_object()
        description = str(page.diary) + ':' + str(page.id) + ':' + page.date
        image_hash = imgurUtil.get_image_hash(description)
        imgurUtil.delete_image(image_hash)
        page.delete()
        return HttpResponseRedirect('/diary/')


class UserFormView(View):
    form_class = UserForm
    template_name = 'registration/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('/login')

        return render(request, self.template_name, {'form': form})

diary/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous"> {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">

  <body>
    <div style="font-family: 'Ubuntu', sans-serif;">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'diary:index' %}">
          <i class="glyphicon glyphicon-book"></i> <b><h3><strong>Dailigram</strong></h3></b>
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        ></button>
          <span id="expand" class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="nav navbar-nav navbar-right ml-auto">
            <li class="nav-item active">
              <a href="{% url 'diary:index' %}" class="nav-link">
                <i class="fa fa-home"></i>
                <span><h5>{{ user.username }}'s diary </h5></span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'diary:create_page' %}" class="nav-link">
                <i class="glyphicon glyphicon-plus"></i> <span id="create"><h5>Create</h5></span>
              </a>
            </li>
            <li class="nav-item">
              <a id="logout" href="{% url 'logout' %}" class="nav-link">
                <i class="glyphicon glyphicon-log-out"></i> <span><h5>Logout</h5></span>
              </a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <br />
    {% block content %}{% endblock %}
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>
    <script>
      function disableUploadButton() {
        document.getElementById("upload-button").disabled = true
      }
      function disableDeleteButton(id) {
        document.getElementById(id).disabled = true
      }
      window.onpageshow = event => {
        if (event.persisted) {
          window.location.reload();
        }
      };
    </script>
  </body>
</html>